/**
 * Contract Markdown renderer — converts ExecutionContractV1 to
 * human-readable Markdown for the git audit trail.
 *
 * Blueprint v3.5 §7: Audit trail must persist contract revisions,
 * governance hash, contract hash, timestamps, and revision lineage.
 *
 * @module 10xs/kernel-runtime/audit/contract-renderer
 */

import type { ExecutionContractV1 } from "../schemas/execution-contract";

/** Render an ExecutionContractV1 as structured Markdown. */
export function renderContractMarkdown(
  contract: ExecutionContractV1,
): string {
  const lines: string[] = [];

  lines.push(`# Execution Contract: ${contract.executionContractId}`);
  lines.push("");
  lines.push(`**Microtask:** ${contract.microtaskId}`);
  lines.push(`**Blueprint Version:** ${contract.blueprintVersion}`);
  lines.push(`**Kernel Version:** ${contract.kernelVersion}`);
  lines.push(`**Revision:** ${contract.revision}`);
  lines.push(`**Created:** ${contract.createdAt}`);
  lines.push("");

  appendIntegrity(lines, contract);
  appendDefinition(lines, contract);
  appendValidation(lines, contract);

  lines.push("---");
  lines.push(
    `*Generated by 10xs Governance Kernel v${contract.kernelVersion}*`,
  );
  lines.push("");

  return lines.join("\n");
}

function appendIntegrity(
  lines: string[],
  contract: ExecutionContractV1,
): void {
  lines.push("## Integrity");
  lines.push("");
  lines.push("| Field | Value |");
  lines.push("|-------|-------|");
  lines.push(`| Governance Hash | \`${contract.governanceHash}\` |`);
  lines.push(`| Contract Hash | \`${contract.contractHash}\` |`);
  if (contract.supersedesExecutionContractId) {
    lines.push(
      `| Supersedes | \`${contract.supersedesExecutionContractId}\` |`,
    );
  }
  lines.push("");
}

function appendDefinition(
  lines: string[],
  contract: ExecutionContractV1,
): void {
  const def = contract.definition;
  lines.push("## Contract Definition");
  lines.push("");
  lines.push(`**Scope:** ${def.scopeSummary}`);
  lines.push("");

  if (def.allowedBoundaries.length > 0) {
    lines.push("### Allowed Boundaries");
    lines.push("");
    for (const b of def.allowedBoundaries) {
      lines.push(`- \`${b}\``);
    }
    lines.push("");
  }

  lines.push("### Acceptance Checklist");
  lines.push("");
  for (const item of def.acceptanceChecklist) {
    lines.push(`- [ ] ${item}`);
  }
  lines.push("");

  lines.push("### Enforcement");
  lines.push("");
  lines.push(def.enforcementSummary);
  lines.push("");
}

function appendValidation(
  lines: string[],
  contract: ExecutionContractV1,
): void {
  lines.push("## Validation");
  lines.push("");
  lines.push(`**Status:** ${contract.validation.result}`);
  if (contract.validation.validatedAt) {
    lines.push(`**Validated:** ${contract.validation.validatedAt}`);
  }
  lines.push("");
}
