/**
 * Report Markdown renderer — converts a completed ExecutionContractV1
 * (with populated reportingTemplate) to human-readable Markdown.
 *
 * Blueprint v3.5 §4: Completion reports are the bridge between
 * execution and validation in the governance loop.
 *
 * @module 10xs/kernel-runtime/audit/report-renderer
 */

import type { ExecutionContractV1 } from "../schemas/execution-contract";
import type { ReportWarning } from "../reporting/report-generator";

/** Render a completion report as structured Markdown. */
export function renderReportMarkdown(
  contract: ExecutionContractV1,
  warnings: ReportWarning[],
  submittedAt: string,
): string {
  const lines: string[] = [];
  const report = contract.reportingTemplate;

  // Header
  lines.push(`# Completion Report: ${contract.executionContractId}`);
  lines.push("");
  lines.push(`**Microtask:** ${contract.microtaskId}`);
  lines.push(`**Contract:** ${contract.executionContractId}`);
  lines.push(`**Submitted:** ${submittedAt}`);
  lines.push(`**Kernel Version:** ${contract.kernelVersion}`);
  lines.push("");

  appendMetrics(lines, report);
  appendFiles(lines, report);
  appendWarnings(lines, warnings);
  appendNotes(lines, report);

  // Footer
  lines.push("---");
  lines.push(
    `*Generated by 10xs Governance Kernel v${contract.kernelVersion}*`,
  );
  lines.push("");

  return lines.join("\n");
}

function appendMetrics(
  lines: string[],
  report: ExecutionContractV1["reportingTemplate"],
): void {
  lines.push("## Metrics");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  lines.push(`| Lines Added | ${report.linesAdded} |`);
  lines.push(`| Lines Removed | ${report.linesRemoved} |`);
  lines.push(`| Time Spent | ${report.timeSpentHours}h |`);
  lines.push(`| Tests Added | ${report.testsAdded} |`);
  lines.push("");
}

function appendFiles(
  lines: string[],
  report: ExecutionContractV1["reportingTemplate"],
): void {
  lines.push("## Files Modified");
  lines.push("");
  if (report.filesModified.length === 0) {
    lines.push("*No files reported.*");
  } else {
    for (const f of report.filesModified) {
      lines.push(`- \`${f}\``);
    }
  }
  lines.push("");
}

function appendWarnings(
  lines: string[],
  warnings: ReportWarning[],
): void {
  if (warnings.length === 0) return;
  lines.push("## Constraint Warnings");
  lines.push("");
  for (const w of warnings) {
    lines.push(`- **${w.field}:** ${w.message}`);
  }
  lines.push("");
}

function appendNotes(
  lines: string[],
  report: ExecutionContractV1["reportingTemplate"],
): void {
  if (!report.riskNotes && !report.complianceDeclaration) return;
  lines.push("## Notes");
  lines.push("");
  if (report.riskNotes) {
    lines.push(`**Risk Notes:** ${report.riskNotes}`);
    lines.push("");
  }
  if (report.complianceDeclaration) {
    lines.push(`**Compliance:** ${report.complianceDeclaration}`);
    lines.push("");
  }
}
