/**
 * MT-3.5C-02: Validation Markdown renderer — converts a ValidationResult
 * to human-readable Markdown for the git audit trail.
 *
 * Blueprint v3.5 §7: Audit trail must persist validation outcomes.
 * CTO Directive 3.5C §4: "Maintain symmetry with contracts and reports."
 *
 * @module 10xs/kernel-runtime/audit/validation-renderer
 */

import type {
  ExecutionContractV1,
  ValidationResult,
} from "../schemas/execution-contract";

/** Render a validation result as structured Markdown. */
export function renderValidationMarkdown(
  contract: ExecutionContractV1,
  validationResult: ValidationResult,
  enforcementMode: "warn" | "block",
  canTransitionToDone: boolean,
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Validation Result: ${contract.executionContractId}`);
  lines.push("");
  lines.push(`**Microtask:** ${contract.microtaskId}`);
  lines.push(`**Contract:** ${contract.executionContractId}`);
  lines.push(`**Result:** ${validationResult.result}`);
  lines.push(`**Enforcement Mode:** ${enforcementMode}`);
  lines.push(
    `**Can Transition to Done:** ${canTransitionToDone ? "Yes" : "No"}`,
  );
  if (validationResult.validatedAt) {
    lines.push(`**Validated:** ${validationResult.validatedAt}`);
  }
  lines.push(`**Kernel Version:** ${contract.kernelVersion}`);
  lines.push("");

  appendViolations(lines, validationResult);
  appendWarnings(lines, validationResult);
  appendSummary(lines, validationResult, enforcementMode);

  // Footer
  lines.push("---");
  lines.push(
    `*Generated by 10xs Governance Kernel v${contract.kernelVersion}*`,
  );
  lines.push("");

  return lines.join("\n");
}

function appendViolations(
  lines: string[],
  result: ValidationResult,
): void {
  if (result.violations.length === 0) return;
  lines.push("## Violations");
  lines.push("");
  lines.push("| Field | Message | Actual | Limit |");
  lines.push("|-------|---------|--------|-------|");
  for (const v of result.violations) {
    lines.push(`| ${v.field} | ${v.message} | ${v.actual} | ${v.limit} |`);
  }
  lines.push("");
}

function appendWarnings(
  lines: string[],
  result: ValidationResult,
): void {
  if (result.warnings.length === 0) return;
  lines.push("## Warnings");
  lines.push("");
  for (const w of result.warnings) {
    lines.push(`- **${w.field}:** ${w.message}`);
  }
  lines.push("");
}

function appendSummary(
  lines: string[],
  result: ValidationResult,
  enforcementMode: "warn" | "block",
): void {
  lines.push("## Summary");
  lines.push("");
  lines.push(`- **Total violations:** ${result.violations.length}`);
  lines.push(`- **Total warnings:** ${result.warnings.length}`);
  lines.push(`- **Enforcement:** ${enforcementMode}`);
  if (enforcementMode === "block" && result.violations.length > 0) {
    lines.push(
      "- **Action:** Task BLOCKED — violations must be resolved before done",
    );
  } else if (result.violations.length > 0) {
    lines.push(
      "- **Action:** Violations recorded — task may proceed (warn mode)",
    );
  } else if (result.warnings.length > 0) {
    lines.push("- **Action:** Warnings noted — no blocking issues");
  } else {
    lines.push("- **Action:** All constraints satisfied");
  }
  lines.push("");
}
